#ifndef CVT_ICOLORCODEMAP_H
#define CVT_ICOLORCODEMAP_H

namespace cvt {

	enum IColorCodeMap {
		ICOLORCODE_PM3D,
		ICOLORCODE_HOT,
		ICOLORCODE_OCEAN,
		ICOLORCODE_GRAY,
		ICOLORCODE_COLORGRAYPRINT,
		ICOLORCODE_RAINBOW,
		ICOLORCODE_AUTUMN
	};
}

#endif
