X( cl_context,		 ::clRetainContext,		 ::clReleaseContext )
X( cl_command_queue, ::clRetainCommandQueue, ::clReleaseCommandQueue )
X( cl_mem,			 ::clRetainMemObject,	 ::clReleaseMemObject )
X( cl_program,		 ::clRetainProgram,		 ::clReleaseProgram )
X( cl_kernel,		 ::clRetainKernel,		 ::clReleaseKernel )
X( cl_event,		 ::clRetainEvent,		 ::clReleaseEvent )
X( cl_sampler,		 ::clRetainSampler,		 ::clReleaseSampler )
