MACRO(CVTTESTS _LIB _OUT )
    ADD_CUSTOM_COMMAND(
        OUTPUT  ${CMAKE_CURRENT_SOURCE_DIR}/${_OUT}
        COMMAND ${CMAKE_SOURCE_DIR}/util/extracttests.sh
                ${CMAKE_BINARY_DIR}/${_LIB}
		${CMAKE_CURRENT_SOURCE_DIR}/${_OUT}
        DEPENDS ${CMAKE_BINARY_DIR}/${_LIB}
    )
ENDMACRO(CVTTESTS)

