# include once:
IF(LIBRARYCONFIG)
	return()
ENDIF(LIBRARYCONFIG)

SET(LIBRARYCONFIG TRUE)

# postfix for debug builds
SET(LIBRARY_POSTFIX_DEBUG "_d")

INCLUDE(GLCLTOHEADER)

# add source, current source and binary dir to search for includes
INCLUDE_DIRECTORIES(
	${CMAKE_SOURCE_DIR}
	${CMAKE_CURRENT_SOURCE_DIR}
	${CMAKE_BINARY_DIR}
)

IF(${CMAKE_BUILD_TYPE})
	MESSAGE(FATAL_ERROR "Build type is empty.")
ENDIF(${CMAKE_BUILD_TYPE})

# put libs/archives into lib folder and executables into bin
SET(EXECUTABLE_OUTPUT_PATH "${CMAKE_BINARY_DIR}/bin")
SET(RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
SET(LIBRARY_OUTPUT_PATH "${CMAKE_BINARY_DIR}/lib")
SET(ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
SET(LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
SET(LIB_VERSION "0.1")
