# Macro for configuring a library module (sublibrary)
MACRO(MODULE_CONFIGURATION
	MODULE_NAME
	MODULE_HEADERS
	MODULE_SOURCES
	LINKER_DEPENDENCIES
)
	
	MESSAGE(STATUS "Configuring module: ${MODULE_NAME}")
	
	SET(${MODULE_NAME}_ALL 
		${MODULE_HEADERS}
		${MODULE_SOURCES}
	)

	ADD_LIBRARY("${MODULE_NAME}" ${${MODULE_NAME}_ALL})
	
	TARGET_LINK_LIBRARIES("${MODULE_NAME}" ${LINKER_DEPENDENCIES})
	
	SET_TARGET_PROPERTIES("${MODULE_NAME}" PROPERTIES VERSION ${LIB_VERSION})
	
	SET_TARGET_PROPERTIES("${MODULE_NAME}" PROPERTIES DEBUG_POSTFIX "${LIBRARY_POSTFIX_DEBUG}")	
	
#	SET_TARGET_PROPERTIES("${MODULE_NAME}" PROPERTIES FRAMEWORK TRUE)	

	#PREFIX hack for needed for Xcode and MVSC Projects
	IF( ${CMAKE_GENERATOR} MATCHES "Xcode" )
		SET_TARGET_PROPERTIES("${MODULE_NAME}" PROPERTIES PREFIX "../")	
	ENDIF()

	INSTALL(TARGETS "${MODULE_NAME}"
			LIBRARY DESTINATION lib
#FRAMEWORK DESTINATION lib
			COMPONENT ${MODULE_NAME}
	)

	GET_FILENAME_COMPONENT(folderName ${CMAKE_CURRENT_SOURCE_DIR} NAME)
	#install header
	foreach(HEADER_FILE ${MODULE_HEADERS})
		GET_FILENAME_COMPONENT(pathName "${HEADER_FILE}" PATH)
		INSTALL(FILES "${HEADER_FILE}" 
				DESTINATION "include/${folderName}/${pathName}" 
				COMPONENT Headers
		)
	endforeach(HEADER_FILE)
ENDMACRO(MODULE_CONFIGURATION)
